package ma.ac.emi.tiles;

public enum TileType {
    TOP_LEFT_OUT, TOP_RIGHT_OUT, BOTTOM_LEFT_OUT, BOTTOM_RIGHT_OUT, 
    TOP_LEFT_IN, TOP_RIGHT_IN, BOTTOM_LEFT_IN, BOTTOM_RIGHT_IN,
    
    TOP_EDGE_OUT, BOTTOM_EDGE_OUT, LEFT_EDGE_OUT, RIGHT_EDGE_OUT,
    TOP_EDGE_IN, BOTTOM_EDGE_IN, LEFT_EDGE_IN, RIGHT_EDGE_IN,
    
    VOID,
    
    DOOR,

    BORDER,

    GROUND_DEFAULT,
    GROUND_VAR_1_OBS,
    GROUND_VAR_2_OBS,
    GROUND_VAR_3_OBS,
    GROUND_VAR_4_OBS,
    GROUND_VAR_5_OBS
}
